import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('.qa', {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const errors=[];
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage(); page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 await page.locator('.ouroboros-intro').waitFor({state:'visible'});
 assert.equal(await page.locator('[data-portfolio-content]').evaluate(el=>el.inert),true);
 await page.waitForTimeout(650); await page.screenshot({path:'.qa/intro-entry.png'});
 await page.waitForTimeout(900); await page.screenshot({path:'.qa/intro-coil.png'});
 await page.locator('.ouroboros-intro').waitFor({state:'hidden',timeout:7000});
 assert.equal(await page.locator('[data-portfolio-content]').evaluate(el=>el.inert),false);
 assert.equal(await page.evaluate(()=>sessionStorage.getItem('afterimage-intro-seen-v1')),'1');
 await page.screenshot({path:'.qa/intro-complete.png'});
 await page.reload({waitUntil:'domcontentloaded'});
 await page.locator('.hero-art.is-ready').waitFor();
 assert.equal(await page.locator('.ouroboros-intro').isVisible(),false,'Repeat visits bypass intro');
 await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const touch=await mobile.newPage(); touch.on('pageerror',e=>errors.push(e.message));
 await touch.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 await touch.getByRole('button',{name:'Skip intro'}).waitFor();
 await touch.waitForTimeout(1200); await touch.screenshot({path:'.qa/intro-mobile.png'});
 await touch.getByRole('button',{name:'Skip intro'}).click();
 await touch.locator('.ouroboros-intro').waitFor({state:'hidden'});
 assert.equal(await touch.evaluate(()=>document.body.style.overflow),'');
 assert.equal(await touch.locator('[data-portfolio-content]').evaluate(el=>el.inert),false);
 await mobile.close();
 const reduced=await browser.newContext({reducedMotion:'reduce'});
 const calm=await reduced.newPage();
 await calm.goto('http://localhost:3000',{waitUntil:'domcontentloaded'});
 assert.equal(await calm.locator('.ouroboros-intro').isVisible(),false);
 assert.equal(await calm.locator('[data-portfolio-content]').evaluate(el=>el.inert),false);
 await reduced.close();
 assert.deepEqual(errors,[]);
 console.log('PASS: intro completion, restored input, once per session, mobile skip, reduced motion; no runtime errors.');
} finally {await browser.close();}
